import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";
import { Layout } from "@/components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Text>Pockets.GG</Text>
      </Layout>
    </>
  );
}
